import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Menu from '@/components/menu/Menu'
import useMenu from '@/hooks/useMenu'

const inter = Inter({ subsets: ['latin'] })

const iconSize = {
  height: '40px',
  width: '40px'
}

export default function Home() {
  const [isFirstContentVisible] = useState(true)
  const [isButtonClicked] = useState(false)
  const [typedText, setTypedText] = useState('')
  const { isMenuOpen, toggleMenu } = useMenu()



  useEffect(() => {
    
      let intervalId = setInterval(() => {
        const originalText = `Welcome to my website! I'm Ivan Lozić, a skilled Full Stack Developer with a passion for crafting exceptional digital experiences.`
        const currentLength = typedText.length
        const remainingText = originalText.slice(currentLength)

        if (remainingText) {
          setTypedText((prevText) => prevText + remainingText.charAt(0))
        } else {
          clearInterval(intervalId)
        }
      }, 45)

      return () => {
        clearInterval(intervalId)
      }
    
  }, [isFirstContentVisible, typedText.length])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <div className={styles.container}>
          <Menu isMenuOpen={isMenuOpen} toggleMenu={toggleMenu} />

          {isFirstContentVisible && (
            <div
              className={`${styles.first} ${
                isButtonClicked ? styles.animateOut : ''
              }`}
            >
              <div className={styles.text}>
                <h1>{typedText}</h1>
              </div>
            </div>
          )}
        </div>
      </main>

    </>
  )
}
